// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"database/sql"
)

// Injectors from wire.go:

// dependency injection to create repo -> service -> handler
func InjectUser(db *sql.DB) *handler {
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository)
	userHandler := ProvideUserHandler(userService)
	return userHandler
}
